//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFrepoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDFrepository_TBL
    {
        public int id { get; set; }
        public byte[] pdf { get; set; }
        public string note { get; set; }
        public Nullable<int> userID { get; set; }
        public string FileName { get; set; }
        public string contentType { get; set; }
    
        public virtual users_TBL users_TBL { get; set; }
    }
}
